# Generated by Django 3.0.4 on 2020-03-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_id', models.CharField(max_length=100)),
                ('goods_sn', models.CharField(max_length=60)),
                ('bar_code', models.CharField(max_length=255)),
                ('goods_name', models.CharField(max_length=120)),
                ('brand_id', models.PositiveIntegerField()),
                ('goods_number', models.PositiveIntegerField()),
                ('is_freepost', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shop_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warn_number', models.IntegerField(blank=True, null=True)),
                ('goods_desc', models.TextField(blank=True, null=True)),
                ('desc_mobile', models.TextField(blank=True, null=True)),
                ('goods_thumb', models.CharField(max_length=255)),
                ('is_on_sale', models.IntegerField()),
                ('is_delete', models.IntegerField()),
                ('status', models.IntegerField()),
                ('pinyin_keyword', models.TextField(blank=True, null=True)),
                ('goods_unit', models.CharField(blank=True, max_length=15, null=True)),
                ('pattern', models.IntegerField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('source_code', models.CharField(blank=True, max_length=255, null=True)),
                ('lifes', models.CharField(blank=True, max_length=255, null=True)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('spec', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsBrand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_letter', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_first_char', models.CharField(blank=True, max_length=1, null=True)),
                ('brand_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('index_img', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_bg', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_desc', models.TextField(blank=True, null=True)),
                ('site_url', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('is_show', models.IntegerField(blank=True, null=True)),
                ('is_delete', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('name_pinyin', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'goods_brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('cat_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=90)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sort_order', models.PositiveIntegerField(blank=True, null=True)),
                ('is_show', models.IntegerField(blank=True, null=True)),
                ('style_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('cat_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('pinyin_keyword', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goods_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsGallery',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.PositiveIntegerField(blank=True, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('img_desc', models.SmallIntegerField(blank=True, null=True)),
                ('thumb_url', models.CharField(blank=True, max_length=255, null=True)),
                ('img_original', models.CharField(blank=True, max_length=255, null=True)),
                ('external_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'goods_gallery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_status', models.IntegerField(blank=True, null=True)),
                ('consignee', models.CharField(blank=True, max_length=60, null=True)),
                ('province', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.PositiveIntegerField(blank=True, null=True)),
                ('district', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=60, null=True)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('ship_code', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_no', models.CharField(blank=True, max_length=255, null=True)),
                ('froms', models.CharField(blank=True, max_length=10, null=True)),
                ('rel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('id_num', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_id', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('product_num', models.IntegerField(blank=True, null=True)),
                ('life', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('third_pay_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('third_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('third_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('third_order_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'order_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=11)),
                ('goods_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=60, unique=True)),
                ('company_name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=32)),
                ('user_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frozen_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reg_time', models.PositiveIntegerField()),
                ('auth_status', models.PositiveIntegerField()),
                ('private_key', models.TextField()),
                ('public_key', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
