# Generated by Django 3.0.4 on 2020-03-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderInfo',
        ),
        migrations.DeleteModel(
            name='UserGoods',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
