# Generated by Django 3.0.4 on 2020-03-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200325_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='desc',
            field=models.CharField(max_length=255, null=True, verbose_name='备注'),
        ),
    ]
