# Generated by Django 3.0.4 on 2020-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_menu_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=255, null=True, verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(to='system.Menu'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
