# Generated by Django 3.0.4 on 2020-03-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20200325_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.IntegerField(choices=[(1, '菜单'), (2, '接口')], default=1, verbose_name='类型'),
        ),
    ]
