# Generated by Django 3.0.4 on 2020-03-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20200326_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
