# Generated by Django 3.0.4 on 2020-03-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20200326_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
