# Generated by Django 3.0.4 on 2020-03-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_remove_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(to='system.Menu', verbose_name='关联菜单'),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='django_menu',
        ),
        migrations.AlterModelTable(
            name='role',
            table='django_role',
        ),
        migrations.AlterModelTable(
            name='user',
            table='django_user',
        ),
    ]
