# Generated by Django 3.0.4 on 2020-03-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20200326_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.IntegerField(choices=[(1, '菜单'), (2, '权限')], default=1, verbose_name='类型'),
        ),
    ]
