# Generated by Django 3.0.4 on 2020-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_auto_20200330_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='昵称'),
        ),
    ]
