# Generated by Django 3.0.4 on 2020-03-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=60, unique=True)),
                ('company_name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=32)),
                ('user_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frozen_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reg_time', models.PositiveIntegerField()),
                ('auth_status', models.PositiveIntegerField(choices=[(0, '未认证或认证失败'), (1, '认证通过')])),
                ('private_key', models.TextField()),
                ('public_key', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
