# Generated by Django 3.0.4 on 2020-03-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_status', models.IntegerField(blank=True, null=True)),
                ('consignee', models.CharField(blank=True, max_length=60, null=True)),
                ('province', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.PositiveIntegerField(blank=True, null=True)),
                ('district', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=60, null=True)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('ship_code', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_no', models.CharField(blank=True, max_length=255, null=True)),
                ('froms', models.CharField(blank=True, max_length=10, null=True)),
                ('rel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('id_num', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_id', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('product_num', models.IntegerField(blank=True, null=True)),
                ('life', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('third_pay_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('third_sn', models.CharField(blank=True, max_length=255, null=True)),
                ('third_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('third_order_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'order_info',
                'managed': False,
            },
        ),
    ]
